version: "3"

services:
  gift-list-db:
    image: postgres:13.1-alpine
    env_file:
      - ./api/config/localdocker.env
      - ./secrets/postgres_credentials.env
    ports:
      - "127.0.0.1:8502:5432"

  db-init:
    build: "./db-init"
    env_file:
      - ./api/config/localdocker.env
      - ./secrets/postgres_credentials.env
    volumes:
      - ./db-init/sql:/app/sql
